---
title: "Final Project: GLANCE Study"
author: "Wendy Wang and Ning Li"
date: "Tuesday, March 10, 2015"
output:
  ioslides_presentation:
    fig_caption: yes
    fig_retina: 1
    keep_md: yes
    smaller: yes
---

## Setting up some options

Let's first turn on the cache for increased performance and improved styling
```{r, cache=FALSE}
# Set some global knitr options
library("knitr")
opts_chunk$set(tidy=TRUE, tidy.opts=list(blank=FALSE, width.cutoff=60), cache=TRUE, messages=FALSE)
```

##Outline

**Reference:**

**Navarro S WE, Kantor ED, Zhang Y, Rho J, Song X, Milne GL, Lampe PD, Lampe JW. Randomized trial of glucosamine and chondroitin supplementation on inflammation and oxidative stress biomarkers and plasma proteomics profiles in healthy humans. PLoS One In press.**

- Background
- Study Design and Data Collection 
- Statistical Analysis Plan
- Data Analysis and Results
- Limitations
- Conclusions

##Background

**Glucosamine and Chondroitin (G&C)**

- One of the most popular dietary supplements in the US
- Mostly taken for osteoarthritis (OA)
- Associated with a 27-35% lower incidence of colorectal cancer, a 26-28% lower incidence of lung  cancer, 17% lower overall mortality, and a 13% lower cancer mortality.
- Safe supplements, with no known major adverse side effects.
- Regular dose
  - 1500 mg/d glucosamine hydrochloride (GHCl) + 1200 mg/d chondroitin sulfate (CS)

##Background

**Mechanisms of G&C on cancer prevention**

- Several lines of evidence from *in vitro* and preclinical studies support a possible role for G&C in reducing inflammation.
- Potentially through inhibition of nuclear factor kappa B pathway.
- No human intervention trials have been evaluated the effect of G&C on reducing inflammation or altering other pathways in healthy individuals

##Study Design

##Participants

##Data collection

##Proteomics Analysis


